license = "MPL-2.0"

modLoader = "javafml"
loaderVersion = "[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "lunalna"
description = "Allows using key modifiers in every Minecraft key binding."

#noinspection ModsTomlValidation
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "modifier_keybinds.mixins.json"

[[dependencies."${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
